# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrycode',
            fields=[
                ('country_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=45)),
            ],
        ),
    ]
