# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setMsg', '0002_alertclntcount_alertclntsession_alertcodemsg_alertemma_alertinfo_alertlog201612_alertlog201701_alert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countrycode',
            new_name='CountrycodeInfo',
        ),
        migrations.RenameModel(
            old_name='Transmission',
            new_name='TransmissionInfo',
        ),
    ]
