# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setMsg', '0005_countrycodeinfo_transmissioninfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countrycodeinfo',
            table='countrycodeinfo',
        ),
        migrations.AlterModelTable(
            name='transmissioninfo',
            table='transmissioninfo',
        ),
    ]
